name = "kvshort"
compatibility_date = "2024-04-05"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
API_KEY = "s3cr3t"

[[kv_namespaces]]
binding = "KV"
id = "8fca5c24892d4b53bf1be5d9af008e89"
